name = "armv9"
defaultTargets = ["Armv9"]
moreLeanArgs = ["--tstack=400000"]

[[lean_lib]]
name = "Armv9"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "nightly-testing-2025-04-07"