name: Build ARM For Lean

on:
  schedule:
    - cron: "42 * * * *"
  workflow_dispatch:

env:
  OPAMVERBOSE: 1
  CLEAR_GLOBS_FILE: .github/workflows/clear-globs.txt

jobs:
  build:
    strategy:
      matrix:
        version: [5.2.1]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Checkout SAIL
      run: |
        git clone https://github.com/rems-project/sail.git
        cd sail
        patch -p1 < ../.github/workflows/sail.patch
        cd ..

    - name: System dependencies (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install build-essential libgmp-dev z3 cvc4 opam

    - name: Restore cached opam
      id: cache-opam-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-${{ matrix.version }}

    - name: Setup opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      run: |
        opam init --yes --no-setup --shell=sh --compiler=${{ matrix.version }}
        opam install dune

    - name: Save cached opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      id: cache-opam-save
      uses: actions/cache/save@v4
      with:
        path: ~/.opam
        key: ${{ steps.cache-opam-restore.outputs.cache-primary-key }}

    - name: Install Sail
      run: |
        eval $(opam env)
        (cd sail; opam install sail --deps-only --yes)
        (cd sail; make install)

    - name: Build the Sail ARM v9.4a Model for Lean
      continue-on-error: true
      run: |
        git clone https://github.com/opencompl/sail-arm.git -b push-klnnlzrtlkzo
        ls
        cd sail-arm
        ls
        patch -p1 <  ../.github/workflows/sail-arm.patch
        cd arm-v9.4-a
        eval $(opam config env)
        make lean VERBOSE_FLAG=
        cd ../..

    - name: Use Lean to build the model and record errors
      continue-on-error: true
      run: |
        wget -q https://raw.githubusercontent.com/leanprover-community/mathlib4/master/scripts/install_debian.sh
        bash install_debian.sh ; rm -f install_debian.sh
        source ~/.profile
        cp README.md.template sail-arm/arm-v9.4-a/lean/armv9
        cp report.py sail-arm/arm-v9.4-a/lean/armv9
        cd sail-arm/arm-v9.4-a/lean/armv9
        (lake build | tee build_log.txt || true)
        cp README.md.template README.md
        ./report.py >> README.md
        cd ../../../..
  
    - name: Compress files
      continue-on-error: true
      run: |
        sed -i -e 's/        /\t/g' sail-arm/arm-v9.4-a/lean/armv9/Armv9.lean
        sed -i -e 's/        /\t/g' sail-arm/arm-v9.4-a/lean/armv9/Armv9/DecodeEnd.lean
        sed -i -e 's/        /\t/g' sail-arm/arm-v9.4-a/lean/armv9/Armv9/SysregsAutogen.lean

    - name: Add build errors
      continue-on-error: true
      run: |
        tail -n 50 sail-arm/arm-v9.4-a/lean/armv9/build_log.txt >> sail-arm/arm-v9.4-a/lean/armv9/README.md

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: main
        FOLDER: sail-arm/arm-v9.4-a/lean/armv9
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: .
